### ISSUE TITLE
CSS error handling bug

### ISSUE THREAD

**Issue by niflostancu** [StartPolymer/gulp-html-postcss#2]
Hi,

When the CSS parser encounters a syntax error, **gulp-html-postcss** throws an unmeaningful exception:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: no writecb in Transform class
    at afterTransform (_stream_transform.js:70:33)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Immediate._onImmediate (CENSORED_ROOT/node_modules/gulp-html-postcss/index.js:82:11)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

If I insert `console.log(error);` inside the plugin's `handleError` function, the error is revealed:

```
{ [Error: CENSORED_ROOT/webapp/themes/default-theme/theme.html:4:3: Failed to find 'components/pagexxx' from CENSORED_ROOT
```

My guess is that the `cb` function is called twice (by both `handleError` and `cb(null, file)` at the end of the `_transform` method), and node throws that generic error instead of the captured one.

Encountered this problem on both Windows/Linux and NodeJS versions _5.0.0_ and _4.3.2_.
Using the latest release of this plugin (6.0.1).

**Comment by aleist** [comment]
I have run into the same error. It is triggered by Polymer custom CSS mixin definitions (not their application) of the form:

```
selector {
  --mixin-name: {
    /* rules */
  };
}
```

Mixins are impossible to avoid in the HTML generated by at least Polymer.dart (not sure about Polymer.js) for apps that use any polymer elements, as the Polymer transformer inlines HTML imports and mixins are widely used in the polymer elements library.

**Comment by JosefJezek** [comment]
@aleist @niflostancu updated to v7.0.0
