### ISSUE TITLE
Add CI services

### ISSUE THREAD

**Issue by gucong3000** [StartPolymer/gulp-html-postcss#9]
`gulp-html-postcss` is ready for travis-ci services.
Can you configure it?

Everything seems to be working right under my account: https://travis-ci.org/gucong3000/gulp-postcss/

**Comment by gucong3000** [comment]
I am looking forward to your release of a new version, which I will rely on in our company's projects.

**Comment by JosefJezek** [comment]
I created new version. I will configure travis-ci.

Thank you for PRs

**Comment by gucong3000** [comment]
Will you publish it to `npm`?

**Comment by gucong3000** [comment]
I added the build status and coverage icon in my fork.
https://github.com/gucong3000/gulp-postcss#readme

**Comment by JosefJezek** [comment]
@gucong3000 CircleCI result is with 1 error...
```
1) PostCSS Syntax Infer should show error for `MODULE_NOT_FOUND`:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
https://circleci.com/gh/StartPolymer/gulp-html-postcss/2

**Comment by gucong3000** [comment]
circleci need a config file.

I was add [config file of travis-ci](https://github.com/StartPolymer/gulp-html-postcss/blob/master/.travis.yml)

**Comment by gucong3000** [comment]
![image](https://user-images.githubusercontent.com/1171691/27939383-dbc6c9d8-62f6-11e7-8720-ef792beae567.png)

**Comment by gucong3000** [comment]
If you trust me, you can authorize me to configure.
This requires administrator privileges

**Comment by JosefJezek** [comment]
I sent you invite to this repo. Please push circle.yml. Thank you.

**Comment by gucong3000** [comment]
It's all set up.
Happy cooperation.
